name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      # Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка системных зависимостей
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-0 libegl1 libopengl0 libx11-xcb1 libxkbcommon-x11-0 libglu1-mesa-dev libxcb-glx0 libfontconfig1 libdbus-1-3 libxcomposite1 libxrandr2 libxrender1 libxtst6 libssl-dev libfreetype6 xvfb

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Установка Python-зависимостей
      - name: Install dependencies
        run: |
          sudo apt-get install -y xvfb
          pip install -r requirements.txt
          pip install pytest-xvfb

      # Запуск тестов
      - name: Run tests
        run: |
          export DISPLAY=:99
          Xvfb :99 &
          pytest
        env:
          DISPLAY: :99
