name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Set DISPLAY environment variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV
      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Start xvfb
        run: Xvfb :99 -screen 0 1280x1024x24 &

      # Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Установка системных зависимостей
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-0 libegl1 libopengl0 libx11-xcb1 libxkbcommon-x11-0 libglu1-mesa-dev libxcb-glx0 libfontconfig1 libdbus-1-3 libxcomposite1 libxrandr2 libxrender1 libxtst6 libssl-dev libfreetype6 xvfb

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Создание и активация виртуального окружения
      - name: Set up virtual environment
        run: python -m venv venv
      - name: Set up virtual environment_2
        run: source venv/bin/activate

      # Установка Python-зависимостей
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-xvfb

      # Запуск тестов
      - name: Run tests
        run: pytest
